# Generated by Django 5.1.6 on 2025-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_student_delete_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='hello@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.TextField(default='sample'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='Maths', max_length=100),
        ),
    ]
