# Generated by Django 5.1.6 on 2025-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('CV', models.FileField(upload_to='cv/')),
                ('Cover_Letter', models.FileField(upload_to='cover_letters/')),
                ('Remark', models.TextField()),
            ],
        ),
    ]
